Change some sentences for better clarity
jquery/jquery pull request #4929
Opened 2021-09-10 17:23 UTC by 1407arjun

## Summary
Issue jquery#4928
Made the following changes in the README.md file:

1. Added a git clone code below the clone instruction.
2. Changed some sentences to sound better.
3. Added an article to the heading tagline.

## Checklist
- [ ] All authors have signed the CLA at https://cla.js.foundation/jquery/jquery
- [ ] New tests have been added to show the fix or feature works
- [ ] Grunt build and unit tests pass locally with these changes
- [ ] If needed, a docs issue/PR was created at https://github.com/jquery/api.jquery.com

Not really sure about the checklist as I'm creating a PR for the first time.

2021-09-10 22:40 UTC, mgol requested changes
Thanks for the contribution but I feel changes in this PR are either not necessary or even wrong so we shouldn't land it.

2021-09-10 22:40 UTC, mgol commented on README.md
> -[jQuery](https://jquery.com/) — New Wave JavaScript
That slogan has been there for 15 years; I'm not sure there's a need to change it now.

2021-09-10 22:40 UTC, mgol commented on README.md
> +Environments which support jQuery
This is not correct. Those environments are not doing anything specifically to support jQuery, it's jQuery that make sure it works fine in those environments.

2021-09-10 22:40 UTC, mgol commented on README.md
> +To build your own jQuery, you need to have the latest Node.js/npm and git 1.7 or later. Earlier versions might work, but are not supported.
Why "your own"? I don't see an issue with the previous text.

2021-09-10 22:40 UTC, mgol commented on README.md
> +```
We've had a concrete instruction in the past but we've deleted that on purpose to not maintain that piece of the documentation considering how many ways there are to clone the repo. The link above should suffice.

2021-09-10 22:40 UTC, mgol commented on README.md
> +Any module may be excluded except for the `core`, and `selector` modules. To exclude a module, pass its path relative to the `src` folder (without the `.js` extension).
`core` is the name here, why do we need the article? We're not writing "the Firefox". "except for" also suggests what's mentioned are modules.

2021-09-10 22:40 UTC, mgol commented on README.md
> +To create a custom build, first check out the build version:
this is not a version of the build but version of jQuery; we're checking out a tag in the repository.

2021-09-10 22:40 UTC, closed without merging

2022-04-11 15:01 UTC, goarblt commented
hello
https://www.evil.com

2022-04-11 15:03 UTC, goarblt commented
hello
https://www.evil.com