Fix splice on non Array
jquery/jquery pull request #4986
Opened 2021-12-17 16:50 UTC by bubbatls

Without this fix it does that

TypeError: results.splice is not a function
    at Function.jQuery.uniqueSort (https://code.jquery.com/jquery-git.js:664:12)
    at jQuery.fn.init.find (https://code.jquery.com/jquery-git.js:2394:27)
    at gocusihafe.js:3:4

Reproduced here:
https://jsbin.com/gocusihafe/1/edit?html,css,js,console,output

### Summary ###

### Checklist ###

* [ ] New tests have been added to show the fix or feature works
* [ ] Grunt build and unit tests pass locally with these changes
* [ ] If needed, a docs issue/PR was created at https://github.com/jquery/api.jquery.com

2021-12-17 21:27 UTC, timmywil commented
Thanks for opening a pull request! It seems we forgot to change our use of splice when [removing it from the jQuery object](https://github.com/jquery/jquery/pull/4473). We did take care of sort and push, just not splice. I'm surprised our tests didn't catch this, but we're going to need to add a test.

Something like the case in the jsbin will work fine to get duplicates on the jQuery object (i.e. `jQuery('body div').find('div')`). A relatively pointless call to `find` as it won't find anything new, but it does the job here of inserting duplicates. That said, there are a lot of divs on the test page, so it would be good to limit it to smaller selection. Something like `jQuery("#moretests div").find("div")` should work.

Also, splice should be its own var file, just like with [sort](https://github.com/jquery/jquery/blob/main/src/var/sort.js)

Thanks!

2021-12-29 18:29 UTC, mgol commented
@bubbatls Hey, are you interested in addressing Timmy's concerns?

2022-01-05 11:08 UTC, mgol commented
@bubbatls Ping. This looks like an issue we'd like to see fixed but to land your PR we need to have Timmy's concerns addressed. If you don't have time for this, please let us know and we'll likely fix this by ourselves.

2022-01-05 14:44 UTC, bubbatls commented
I'm sorry, I was in holiday and after holidays there is a lot of work to do...
Yes I could fix this using your kind of var files, just let me few days.

Thanks

2022-01-05 18:01 UTC, mgol commented
@bubbatls Sure, no problem. Let us know if you hit any roadblocks.

2022-01-11 11:24 UTC, mgol requested changes
Code changes look good now but we still need a test. Can you add one?

@timmywil BTW, I think we can have a simpler & more direct test:
```js
jQuery.uniqueSort( { 0: div, 1: div, length: 2 } );
```
where `div` is a test div appended to `#qunit-fixture`. What do you think? Or maybe we can add both test cases.

2022-01-11 13:00 UTC, bubbatls commented
yes, the test you write is the most unit one about this issue, and the method name is uniqueSort so, checking the "unique" is completely relevant.

But I agree that another one covering more code by doing the .find('div').find('div') is worth being written for potential future regression.

This test should be written in the test/unit/selector.js file?

2022-01-11 13:39 UTC, mgol commented
> This test should be written in the test/unit/selector.js file?

Yes, the both tests should be written in `test/unit/core.js` but in separate `QUnit.test` blocks as they're testing two different things.

2022-01-15 00:28 UTC, mgol commented
EDIT: I made a typo and I mentioned~~`test/unit/core.js`~~ instead of the proper `test/unit/selector.js`; I fixed the comment now.

2022-01-17 14:32 UTC, bubbatls commented
I'm sorry but I spend some time to try to understand how to run the tests before modifying anything. But I have always the error :
test/data/qunit-fixture.js net::ERR_ABORTED 404 (Not Found)
And I don't understand what I'm doing wrong.

2022-01-17 14:52 UTC, mgol commented
How are you running the tests?

You need to build before running the tests as the build process creates a few test files and also builds jQuery and the built version is what gets tested by default. Run `npm run build` before running the tests.

2022-01-24 16:54 UTC, mgol approved these changes
Just some style nits but otherwise looks good, thanks! It's nice you found an existing broken test.

2022-01-24 16:54 UTC, mgol commented on test/unit/selector.js
> +		//we duplicate the test.input, because if not it is modified by the uniqueSort and the second test becomes worthless
```suggestion
		// We duplicate `test.input` because otherwise it is modified by `uniqueSort`
		// and the second test becomes worthless.
```

2022-01-24 16:54 UTC, mgol commented on test/unit/selector.js
> +    assert.deepEqual( jQuery.uniqueSort( test.input.slice( 0 ) ).slice( 0, length ), test.expected, label + " (array)" );
```suggestion
		assert.deepEqual( jQuery.uniqueSort( test.input.slice( 0 ) ).slice( 0, length ), test.expected, label + " (array)" );
```

2022-01-24 17:15 UTC, timmywil approved these changes
Looks good now. Thanks for the tests.

2022-01-24 17:22 UTC, mgol commented on test/unit/selector.js
> +		assert.deepEqual( jQuery.uniqueSort( new Arrayish( test.input ) ).sliceForTestOnly( 0, length ), test.expected, label + " (quasi-array)" );
```suggestion
		assert.deepEqual( jQuery.uniqueSort( test.input.slice( 0 ) ).slice( 0, length ),
			test.expected, label + " (array)" );
		assert.deepEqual( jQuery.uniqueSort( new Arrayish( test.input ) ).sliceForTestOnly( 0, length ),
			test.expected, label + " (quasi-array)" );
```

2022-01-24 17:55 UTC, merged

2022-01-25 06:40 UTC, bubbatls commented
Nice! thanks you all :)

2022-04-11 15:01 UTC, goarblt commented
hello
https://www.evil.com