Build: Make sure `*.cjs` & `*.mjs` files use UNIX line endings as well
jquery/jquery pull request #5290
Opened 2023-07-10 15:33 UTC by mgol

### Summary ###

We've had this rule for `*.js` files so far but we now have two new JS extensions.

Another option is to set this for all text files, not just JS. Is there any downside? AFAIK most Windows editors/IDEs should handle LF line endings just fine nowadays?

### Checklist ###

* ~~New tests have been added to show the fix or feature works~~
* ~~If needed, a docs issue/PR was created at https://github.com/jquery/api.jquery.com~~

2023-07-10 16:19 UTC, timmywil approved these changes

2023-07-10 16:19 UTC, merged

2023-07-10 16:21 UTC, mgol commented
Landed on `main` in 198b41c8c2cd726b875615023b2b37b213040ad3 and on `3.x-stable` in 3c18c1f33cfc69e1e1bd1410ab5176b2abc5fe3a.

2023-08-06 13:22 UTC, jose8109 commented
stop

2023-08-06 13:23 UTC, jose8109 requested changes
stop